export const homeAbout = [
  {
    id: 1,
    cover: "https://img.icons8.com/dotty/80/000000/storytelling.png",
    title: "Best Learning",
    desc: "A great learning experience is one that leaves a lasting impact on an individual's life. It can be an experience that challenges them to think differently or pushes them to develop new skills.",
  },
  {
    id: 1,
    cover: "https://img.icons8.com/ios/80/000000/diploma.png",
    title: "Our experienced",
    desc: "An experienced and qualified teacher can make a significant difference in a student's learning journey. Such a teacher possesses a wealth of knowledge and skills acquired through years of teaching and professional development.",
  },
  {
    id: 1,
    cover: "https://img.icons8.com/ios/80/000000/athlete.png",
    title: "Success",
    desc: "Success is a journey, not a destination. It requires hard work, dedication, and persistence. Success is not just about achieving material wealth or fame; it's about finding fulfillment in life.",
  },
];
export const awrapper = [
  {
    cover:
      "../images/icons/room.png",
    data: "80",
    title: "CLASS ROOMS",
  },

  {
    cover: "../images/icons/teacher.png",
    data: "85",
    title: "TEACHER",
  },
  {
    cover:
      "../images/icons/hand.png",
    data: "10",
    title: "COLLABORATION",
  },
  {
    cover: "../images/icons/lab.png",
    data: "6",
    title: "LABS",
  },
];
export const coursesCard = [
  {
    id: 1,
    cover: "../images/courses/c1.png",
    coursesName: "Introducing to Lorem Course Name",
    courTeacher: [
      {
        dcover: "./images/back.webp",
        name: "by John Smith",
        totalTime: "50 lectures (190 hrs)",
      },
    ],
    priceAll: "Rs: 1000 All Course",
    pricePer: "Rs: 15 per month",
  },
  {
    id: 2,
    cover: "../images/courses/c2.png",
    coursesName: "Introducing to Lorem Course Name",
    courTeacher: [
      {
        dcover: "./images/back.webp",
        name: "by Ram Gurung",
        totalTime: "30 lectures (125 hrs)",
      },
    ],
    priceAll: "Rs: 2000 All Course",
    pricePer: "Rs: 25 per month",
  },
  {
    id: 3,
    cover: "../images/courses/c3.png",
    coursesName: "Introducing to Lorem Course Name",
    courTeacher: [
      {
        dcover: "./images/back.webp",
        name: "by Saroj Nepal",
        totalTime: "50 lectures (50 hrs)",
      },
    ],
    priceAll: "Rs: 500 All Course",
    pricePer: "Rs: 50  per month",
  },
  {
    id: 4,
    cover: "../images/courses/c4.png",
    coursesName: "Introducing to Lorem Course Name",
    courTeacher: [
      {
        dcover: "./images/back.webp",
        name: "by Prabin Thapa Mager",
        totalTime: "20 lectures (20 hrs)",
      },
    ],
    priceAll: "$30 All Course",
    pricePer: "$3 per month",
  },
  {
    id: 5,
    cover: "../images/courses/c5.png",
    coursesName: "Introducing to Lorem Course Name",
    courTeacher: [
      {
        dcover: "./images/back.webp",
        name: "by Sunil Bishowkaram",
        totalTime: "100 lectures (150 hrs)",
      },
    ],
    priceAll: "$300 All Course",
    pricePer: "$30 per month",
  },
  {
    id: 6,
    cover: "../images/courses/c6.png",
    coursesName: "Introducing to Lorem Course Name",
    courTeacher: [
      {
        dcover: "./images/back.webp",
        name: "by Sunil Bishowkaram",
        totalTime: "200 lectures (300 hrs)",
      },
    ],
    priceAll: "$500 All Course",
    pricePer: "$80 per month",
  },
  {
    id: 7,
    cover: "../images/courses/c7.png",
    coursesName: "Introducing to Lorem Course Name",
    courTeacher: [
      {
        dcover: "./images/back.webp",
        name: "by Price",
        totalTime: "20 lectures (50 hrs)",
      },
    ],
    priceAll: "$20 All Course",
    pricePer: "$2 per month",
  },
  {
    id: 8,
    cover: "../images/courses/c8.png",
    coursesName: "Introducing to Lorem Course Name",
    courTeacher: [
      {
        dcover: "./images/back.webp",
        name: "by Petter",
        totalTime: "80 lectures (200 hrs)",
      },
    ],
    priceAll: "$200 All Course",
    pricePer: "$40 per month",
  },
  {
    id: 9,
    cover: "../images/courses/c9.png",
    coursesName: "Introducing to Lorem Course Name",
    courTeacher: [
      {
        dcover: "./images/back.webp",
        name: "by Petter",
        totalTime: "50 lectures (50 hrs)",
      },
    ],
    priceAll: "$20 All Course",
    pricePer: "$3 per month",
  },
];
export const online = [
  {
    cover: "./images/courses/online/o7.png",
    hoverCover: "./images/courses/online/o7.1.png",
    courseName: "Medical",
    course: "Courses",
    path: [
      "Medical Officer",
      "Nurse",
      "Surgeon",
      "Dentist",
      "Pharmacist",
      "Physical Therapist",
      "and many more",
    ],
  },

  {
    cover: "./images/courses/online/o4.png",
    hoverCover: "./images/courses/online/o4.1.png",
    courseName: "Non Medical",
    course: "Courses",
    path: [
      "Engineering",
      "Architecture",
      "Mathematics/Statistics",
      "Education & Teaching",
      "Computer Science",
      "Hotel Management",
      "and many more",
    ],
  },
  {
    cover: "./images/courses/online/o11.png",
    hoverCover: "./images/courses/online/o11.1.png",
    courseName: "Commerce",
    course: "Courses",
    path: [
      "Chartered Accountancy",
      "Bachelor of Commerce",
      "Investment Banking",
      "Cost accounting",
      "Finance",
      "and many more",
    ],
  },
  {
    cover: "./images/courses/online/o2.png",
    hoverCover: "./images/courses/online/o2.1.png",
    courseName: "Art",
    course: "Courses",
    path: [
      "Art Director",
      "Graphic Designer",
      "Photographer",
      "Interior Designer",
      "Fashion Designer",
      "and many more",
    ],
  },
  {
    cover: "./images/courses/online/o9.png",
    hoverCover: "./images/courses/online/o9.1.png",
    courseName: "PTE",
    course: "Courses",
  },
  {
    cover: "./images/courses/online/o8.png",
    hoverCover: "./images/courses/online/o7.1.png",
    courseName: "ILETS",
    course: "Courses",
  },
  //

  // {
  //   cover: "./images/courses/online/o7.png",
  //   hoverCover: "./images/courses/online/o7.1.png",
  //   courseName: "Health & Fitness",
  //   course: "10 Courses",
  // },
  // {
  //   cover: "./images/courses/online/o8.png",
  //   hoverCover: "./images/courses/online/o8.1.png",
  //   courseName: "Marketing",
  //   course: "30 Courses",
  // },
  // {
  //   cover: "./images/courses/online/o9.png",
  //   hoverCover: "./images/courses/online/o9.1.png",
  //   courseName: "Graphic Design",
  //   course: "80 Courses",
  // },
  // {
  //   cover: "./images/courses/online/o10.png",
  //   hoverCover: "./images/courses/online/o10.1.png",
  //   courseName: "Music",
  //   course: "120 Courses",
  // },
  // {
  //   cover: "./images/courses/online/o11.png",
  //   hoverCover: "./images/courses/online/o11.1.png",
  //   courseName: "Business Administration",
  //   course: "17 Courses",
  // },
  // {
  //   cover: "./images/courses/online/o12.png",
  //   hoverCover: "./images/courses/online/o12.1.png",
  //   courseName: "Web Management",
  //   course: "17 Courses",
  // },
];
export const team = [
  {
    cover: "./images/team/f-1.jpeg",
    name: "MR. Wazir Dhanda (M.D)",
    work: "MA SOCIOLOGY",
  },
  {
    cover: "./images/team/f-2.jpeg",
    name: "MRS. Sudha Sharma (Principal)",
    work: "M.A HISTORY,  M.A ENGLISH, B.ED",
  },
  {
    cover: "./images/team/facultyone.png",
    name: "MONIKA (B.COM TEACHER)",
    work: "DEGREE- PGT-4 COMMERCE , BED, B.COM ,M.COM,CTET",
  },
  {
    cover: "./images/team/facultytwo.png",
    name: "RITU DEVI (HINDI TEACHER)",
    work: "DEGREE-M.A HINDI (HTET) QUALIFIED",
  },
  {
    cover: "./images/team/facultythree.png",
    name: "MANISHA (MATH TEACHER)",
    work: "DEGREE- MSC ,BED ,TGT-MATH",
  },
  {
    cover: "./images/team/Accivementimg2.png",
    name: "HARIOM (SANSKRIT TEACHER)",
    work: "DEGREE-B.A SANSKRIT",
  },
  // {
  //   cover: "./images/team/Accivementimg3.png",
  //   name: "Ph.D Anna Hanzen",
  //   work: "DEVELOPER AND LEAD INSTRUCTOR",
  // },
  // {
  //   cover: "./images/team/t8.webp",
  //   name: "Ph.D Brian Wooden",
  //   work: "DEVELOPER AND LEAD INSTRUCTOR",
  // },
];
export const mainTeam = [
  {
    cover: "./images/team/f-1.jpeg",
    name: "Wazir Dhanda (M.D)",
    work: "MA SOCIOLOGY",
  },
  {
    cover: "./images/team/f-2.jpeg",
    name: "(Sudha Sharma) Principal",
    work: "M.A HISTORY,  M.A ENGLISH, B.ED",
  },
];
export const price = [
  {
    name: "BASIC PLAN",
    price: "49K",
    desc: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
  },
  {
    name: "BEGINNER PLAN",
    price: "79K",
    desc: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
  },
  {
    name: "PREMIUM PLAN",
    price: "109k",
    desc: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
  },
  {
    name: "ULTIMATE PLAN",
    price: "149K",
    desc: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
  },
];
export const faq = [
  {
    title: "What steps do you take to overcome academic challenges?",
    desc: "Admissions interviewers may ask this question to determine whether you're prepared to solve problems and succeed in challenging classes. In your answer, you can describe the resources you've used to help you accomplish your goals in classes you've taken. You can also discuss how you might resolve an academic issue if a resource wasn't available.",
  },
  {
    title:
      "Describe a time when you made an ethical decision at school. What did you do?",
    desc: "Interviewers may ask this question to understand how you respond to an ethical issue, such as noticing a classmate cheated on an assignment. In your answer, you could discuss the steps you took to approach your classmate about the situation. You could also describe how you supported your classmate in completing their coursework, such as by offering to help them with their homework.",
  },
  {
    title: "What's your favorite subject? Why?",
    desc: "This question helps the interviewer learn more about your academic history and interests. It also allows them to learn more about your personality and recommend subjects the school offers that you might enjoy. To ensure your answer is unique, consider focusing on how the subject affects you personally.",
  },
  {
    title: "Why did you choose your major?",
    desc: "This question helps interviewers understand if you're prepared for success in your chosen major. They may also ask this question to determine what motivated you to pursue a particular field of study. In your response, explain why you chose your major and what you hope to accomplish with it.",
  },
  {
    title: "What are your academic strengths and weaknesses?",
    desc: "An admissions interviewer may ask this question to understand what you excel at and what areas might need some improvement. In your response, consider explaining how you plan to enhance your skills to help you succeed in your studies. You can also discuss how you've used your strengths to help you overcome your weaknesses.",
  },
  {
    title: "How do you manage stress in an academic environment?",
    desc: "Admissions interviewers often ask this question to predict how you might overcome obstacles in a rigorous academic environment. Consider discussing healthy methods you could use to manage stress and promote a positive mindset. You can also talk about how you've used these strategies in the past.",
  },
];
export const blog = [
  {
    id: 1,
    type: "admin",
    date: "JAN. 18, 2021",
    com: "3 COMMENTS ",
    title: "Build your Dream Software & Engineering Career",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
    cover: "../images/blog/b1.webp",
  },
  {
    id: 2,
    type: "admin",
    date: "API. 25, 2022",
    com: "5 COMMENTS ",
    title: "Build your Dream Software & Engineering Career",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
    cover: "../images/blog/b2.webp",
  },
  {
    id: 3,
    type: "user",
    date: "MAY. 15, 2022",
    com: "10 COMMENTS ",
    title: "Build your Dream Software & Engineering Career",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
    cover: "../images/blog/b3.webp",
  },
  {
    id: 4,
    type: "admin",
    date: "JAN. 02, 2022",
    com: "3 COMMENTS ",
    title: "Build your Dream Software & Engineering Career",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
    cover: "../images/blog/b4.webp",
  },
  {
    id: 5,
    type: "admin",
    date: "DEC. 14, 2022",
    com: "3 COMMENTS ",
    title: "Build your Dream Software & Engineering Career",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
    cover: "../images/blog/b5.webp",
  },
  {
    id: 6,
    type: "user",
    date: "JAN. 18, 2021",
    com: "12 COMMENTS ",
    title: "Build your Dream Software & Engineering Career",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
    cover: "../images/blog/b6.webp",
  },
];
export const testimonal = [
  {
    id: 1,
    name: "Nidhi Nain",
    post: "DSP",
    desc: "Our students thrive, achieving success untold, Their efforts shine bright, turning dreamstogold.With passion and perseverance, they rise above, Embarking on journeys, fueled by knowledge and love.",
    cover: "./images/testo/s1.png",
  },
  {
    id: 2,
    name: "Pryianshu",
    post: "Jee Mains",
    desc: "Our students are a testament to our commitment to excellence. With their hard work and dedication, they have achieved great success in their academic and personal lives. We are proud of their accomplishments and look forward to seeing all that they will achieve in the future. Our mission is to continue to support and inspire all of our students to reach their full potential.",
    cover: "./images/testo/s2.png",
  },
  {
    id: 3,
    name: "Vanshika Bhola",
    post: "Asian Gold Medalist",
    desc: "Our students thrive, achieving great heights,Their hard work and dedication shining bright.Success is their companion, every step they take,Empowered learners, their futures they make.",
    cover: "./images/achievement/Accivementimg3.png",
  },
];

export const facility = ["./images/facility/facility-1.jpg"];

export const students = [
  {
    name: "Nidhi Nain",
    fatheName: "-",
    address: "Ahinka",
    achievements: "DSP",
  },
  {
    name: "Neha Dhanda",
    fatheName: "D/O sh. Wazir",
    address: "Ahinka",
    achievements: "JRF-AIR-22",
  },
  {
    name: "Priyanshee Chahal",
    fatheName: "Sh Kuldeep Singh",
    address: "Barodi",
    achievements: "JEE-MAINS 99.5%",
  },
  {
    name: "Sachin",
    fatheName: "Sh Rajesh",
    address: "Jin",
    achievements: "JEE-MAINS 95%",
  },
  {
    name: "Anjee Khatkar",
    fatheName: "Sh Randhir Singh",
    address: "Mohangarh",
    achievements: "Inspector in H.P",
  },
  // {
  //   name: "Ammit punia",
  //   fatheName: "-",
  //   address: "-",
  //   achievements: "RBI Branch",
  // },
  // {
  //   name: "Sharwan Redhu",
  //   fatheName: "-",
  //   address: "-",
  //   achievements: "Indian Navy Captain",
  // },
  // {
  //   name: "Mohit Redhu",
  //   fatheName: "-",
  //   address: "Shahpur",
  //   achievements: "Indain Army",
  // },
  // {
  //   name: "Aehish Chahal",
  //   fatheName: "Jai Singh",
  //   address: "Barodi",
  //   achievements: "Indain Army",
  // },

  // {
  //   name: "Navdeep Kundu",
  //   fatheName: "Sh Raj Singh",
  //   address: "Ahinka",
  //   achievements: "Air Force",
  // },
  // {
  //   name: "Satyender Redhu",
  //   fatheName: "Sh Swender ",
  //   address: "Kair Kheri",
  //   achievements: "Indain Army",
  // },
  // {
  //   name: "Garwita Sharma",
  //   fatheName: "Sh Naresh",
  //   address: "Jind",
  //   achievements: "Fifth Rank in Haryana",
  // },
  // {
  //   name: "Ravinder",
  //   fatheName: "-",
  //   address: "Ahirka",
  //   achievements: "VLDA",
  // },
  // {
  //   name: "Rakesh",
  //   fatheName: "S/O Sh Balwir",
  //   address: "Jeewanpur",
  //   achievements: "Indain Army",
  // },
  // {
  //   name: "Amit",
  //   fatheName: "S/O Sh. Randhir",
  //   address: "Dolamwala",
  //   achievements: "P.W.D",
  // },
];

export const gallery = [
  "./images/main-gallery/s-1.jpg",
  "./images/main-gallery/s-2.jpg",
  "./images/main-gallery/s-3.jpg",
  "./images/main-gallery/s-4.jpg",
  "./images/main-gallery/s-5.jpg",
  "./images/main-gallery/s-6.jpg",
  "./images/main-gallery/s-7.jpg",
  "./images/main-gallery/s-8.jpg",
  "./images/main-gallery/s-9.jpg",
  "./images/main-gallery/s-10.jpg",
  "./images/main-gallery/s-11.jpg",
  "./images/main-gallery/s-12.jpg",
  "./images/main-gallery/s-13.jpg",
  "./images/main-gallery/s-14.jpg",
  "./images/main-gallery/s-15.jpg",
  "./images/main-gallery/s-16.jpg",
  "./images/main-gallery/s-17.jpg",
  "./images/main-gallery/s-18.jpg",
  "./images/main-gallery/s-19.jpg",
  "./images/main-gallery/s-20.jpg",
  "./images/main-gallery/s-21.jpg",
  "./images/main-gallery/s-22.jpg",
  "./images/main-gallery/s-23.jpg",
  "./images/main-gallery/s-24.jpg",
  "./images/main-gallery/s-25.jpg",
  "./images/main-gallery/s-26.jpg",
  "./images/main-gallery/s-27.jpg",
  "./images/main-gallery/s-28.jpg",
  "./images/main-gallery/s-29.jpg",
  "./images/main-gallery/s-30.jpg",
  "./images/main-gallery/s-31.jpg",
  "./images/main-gallery/s-32.jpg",
  "./images/main-gallery/s-33.jpg",
  "./images/main-gallery/s-34.jpg",
  "./images/main-gallery/s-35.jpg",
  // 
  "./images/main-gallery/sc-1.jpeg",
  "./images/main-gallery/sc-2.jpeg",
  "./images/main-gallery/sc-3.jpeg",
  "./images/main-gallery/sc-4.jpeg",
  "./images/main-gallery/sc-5.jpeg",
  "./images/main-gallery/sc-6.jpeg",
  "./images/main-gallery/sc-7.jpeg",
  "./images/main-gallery/sc-8.jpeg",
  // 
  "./images/main-gallery/g-1.jpg",
  "./images/main-gallery/g-2.jpg",
  "./images/main-gallery/g-3.jpg",
  "./images/main-gallery/g-4.jpg",
  "./images/main-gallery/g-5.jpg",
  "./images/main-gallery/g-6.jpg",
  "./images/main-gallery/g-7.jpg",
  "./images/main-gallery/g-8.jpg",
  "./images/main-gallery/g-9.jpg",
  "./images/main-gallery/g-10.jpg",
  "./images/main-gallery/g-11.jpg",
  "./images/main-gallery/g-12.jpg",
  "./images/main-gallery/g-13.jpg",
  "./images/main-gallery/g-14.jpg",
  "./images/main-gallery/g-15.jpg",
  "./images/main-gallery/g-16.jpg",
  "./images/main-gallery/g-17.jpg",
  "./images/main-gallery/g-18.jpg",
  "./images/main-gallery/g-19.jpg",
  "./images/main-gallery/g-20.jpg",
  "./images/main-gallery/g-21.jpg",
  "./images/main-gallery/g-22.jpg",
  "./images/main-gallery/g-23.jpg",
  "./images/main-gallery/g-24.jpg",
  "./images/main-gallery/g-25.jpg",
  "./images/main-gallery/g-26.jpg",
  "./images/main-gallery/g-27.jpg",
  "./images/main-gallery/g-28.jpg",
  "./images/main-gallery/g-29.jpg",
  "./images/main-gallery/g-30.jpg",
  "./images/main-gallery/g-31.jpg",
  "./images/main-gallery/g-32.jpg",
  "./images/main-gallery/g-33.jpg",
  "./images/main-gallery/g-34.jpg",
  "./images/main-gallery/g-35.jpg",
  "./images/main-gallery/g-36.jpg",
  "./images/main-gallery/g-37.jpg",
  "./images/main-gallery/g-38.jpg",
  "./images/main-gallery/g-39.jpg",
  "./images/main-gallery/g-40.jpg",
  "./images/main-gallery/g-41.jpg",
  "./images/main-gallery/g-42.jpg",
  "./images/main-gallery/g-43.jpg",
  "./images/main-gallery/g-44.jpg",
  "./images/main-gallery/g-45.jpg",
  "./images/main-gallery/g-46.jpg",
  "./images/main-gallery/g-47.jpg",
  "./images/main-gallery/g-48.jpg",
  "./images/main-gallery/g-49.jpg",
  "./images/main-gallery/g-50.jpg",
  "./images/main-gallery/g-51.jpg",
  "./images/main-gallery/g-52.jpg",
  "./images/main-gallery/g-53.jpg",
  "./images/main-gallery/g-54.jpg",
  "./images/main-gallery/g-55.jpg",
  "./images/main-gallery/g-56.jpg",
  "./images/main-gallery/g-57.jpg",
  "./images/main-gallery/g-58.jpg",
  "./images/main-gallery/g-59.jpg",
  "./images/main-gallery/g-60.jpg",
  "./images/main-gallery/g-61.jpg",
  "./images/main-gallery/g-62.jpg",
  "./images/main-gallery/g-63.jpg",
  "./images/main-gallery/g-64.jpg",
  "./images/main-gallery/g-65.jpg",
  "./images/main-gallery/g-66.jpg",
  "./images/main-gallery/g-67.jpg",
  "./images/main-gallery/g-68.jpg",
  "./images/main-gallery/g-69.jpg",
  "./images/main-gallery/g-70.jpg",
  "./images/main-gallery/g-71.jpg",
  "./images/main-gallery/g-72.jpg",
  "./images/main-gallery/g-73.jpg",
  "./images/main-gallery/g-74.jpg",
  "./images/main-gallery/g-75.jpg",
  "./images/main-gallery/g-76.jpg",
  "./images/main-gallery/g-77.jpg",
  "./images/main-gallery/g-78.jpg",
  "./images/main-gallery/g-79.jpg",
  "./images/main-gallery/g-80.jpg",
  "./images/main-gallery/g-80.jpg",
  "./images/main-gallery/g-81.jpg",
  "./images/main-gallery/g-82.jpg",
  "./images/main-gallery/g-83.jpg",
  "./images/main-gallery/g-84.jpg",
  "./images/main-gallery/g-85.jpg",
  "./images/main-gallery/g-86.jpg",
  "./images/main-gallery/g-87.jpg",
  "./images/main-gallery/g-88.jpg",
  "./images/main-gallery/g-89.jpg",
  "./images/main-gallery/g-90.jpg",
  "./images/main-gallery/g-91.jpg",
  "./images/main-gallery/g-92.jpg",
  "./images/main-gallery/g-93.jpg",
  "./images/main-gallery/g-94.jpg",
  "./images/main-gallery/g-95.jpg",
  "./images/main-gallery/g-96.jpg",
  "./images/main-gallery/g-97.jpg",
  "./images/main-gallery/g-98.jpg",
  "./images/main-gallery/g-99.jpg",
  "./images/main-gallery/g-100.jpg",
  "./images/main-gallery/g-101.jpg",
  "./images/main-gallery/g-102.jpg",
  "./images/main-gallery/g-103.jpg",
  "./images/main-gallery/g-104.jpg",
  "./images/main-gallery/g-105.jpg",
  "./images/main-gallery/g-106.jpg",
  "./images/main-gallery/g-107.jpg",
  "./images/main-gallery/g-108.jpg",
  "./images/main-gallery/g-109.jpg",
  "./images/main-gallery/g-110.jpg",
  "./images/main-gallery/g-111.jpg",
  "./images/main-gallery/g-112.jpg",
  "./images/main-gallery/g-113.jpg",
  "./images/main-gallery/g-114.jpg",
  "./images/main-gallery/g-115.jpg",
  "./images/main-gallery/g-116.jpg",
  "./images/main-gallery/g-117.jpg",
  "./images/main-gallery/g-118.jpg",
  "./images/main-gallery/g-119.jpg",
  "./images/main-gallery/g-120.jpg",
  "./images/main-gallery/g-121.jpg",
  "./images/main-gallery/g-122.jpg",
  "./images/main-gallery/g-123.jpg",
  "./images/main-gallery/g-124.jpg",
  "./images/main-gallery/g-125.jpg",
  "./images/main-gallery/g-126.jpg",
  "./images/main-gallery/g-127.jpg",
  "./images/main-gallery/g-128.jpg",
  "./images/main-gallery/g-129.jpg",
  "./images/main-gallery/g-130.jpg",
  "./images/main-gallery/g-131.jpg",
  "./images/main-gallery/g-132.jpg",
  "./images/main-gallery/g-133.jpg",
  "./images/main-gallery/g-134.jpg",
  "./images/main-gallery/g-135.jpg",
  "./images/main-gallery/g-136.jpg",
  "./images/main-gallery/g-137.jpg",
];
